.travis.yml, README.md, doc/release-notes.md, package.json, sample/sample6-custom-decorator/IsLongerThan.ts, sample/sample6-custom-decorator/IsUserAlreadyExist.ts, src/container.ts, src/decorator/decorators.ts, src/index.ts, src/metadata/ConstraintMetadata.ts, src/register-decorator.ts, src/validation/ValidationExecutor.ts, src/validation/Validator.ts, test/functional/custom-decorators.spec.ts, test/functional/nested-validation.spec.ts, test/functional/sync-validation.ts
=> sync validation and api for es6/es5 usage

doc/release-notes.md, src/validation/ValidationExecutor.ts, test/functional/nested-validation.spec.ts
There is a bug in nested validation - when doing nested validation on an array, the validation errors are added directly to the children of the property itself. This means that errors in different objects all appear in the same place.
This PR changes the behaviour such that each child object is given its own error (with the propertyName being their index in the original array) and its children are kept separate from the others.
Let me know if this isn't actually the expected behaviour, or whether my implementation of the fix isn't ideal.
=> Fixed nested validation on arrays outputting incorrectly

README.md, doc/release-notes.md, src/decorator/decorators.ts, src/validation/ValidationExecutor.ts, src/validation/ValidationTypes.ts, test/functional/conditional-validation.spec.ts
This PR covers the addition of a potential @ValidateIf() decorator.
Definition is as follows:
```ts
@ValidateIf((object:any) => boolean)
```
The decorator can be attached to any property with validation rules, and is run by passing the object being validated to the constraint function, which returns a boolean specifying whether or not to validate that property.
Example:
```ts
export class Test {
public conditionalProp:string;
@ValidateIf((o:any) => o.conditionalProp == "value")
@isNotEmpty()
public example:string;
}
let t = new Test()
t.conditionalProp = "other";
let errors = validate(t); // -> produces error as 'example' is not empty.
t.conditionalProp = "value";
errors = validate(t); // -> produces no errors.
```
Let me know your thoughts on this, and if this is a feature you would like …
=> feat: ValidateIf decorator

src/index.ts, src/validation/Validator.ts, test/functional/reject-validation.spec.ts
=> Validate API - promise rejection

README.md, doc/release-notes.md, package.json, src/decorator/decorators.ts, src/validation/ValidationTypes.ts, src/validation/Validator.ts, test/functional/validation-functions-and-decorators.spec.ts
I've run into a use case whereby I'd like to validate the text of an input field being in military time format. This is support by some browsers - please see the MDN docs for time with input https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
However, there is insufficient support across all browsers for this use case. 
It uses a relatively complex regex, and rather than using the matchers validator, this would be somewhat less error-prone and easier to use.
=> adding military time validator

README.md, sample/sample1-simple-validation/Post.ts, sample/sample1-simple-validation/app.ts, src/decorator/decorators.ts, src/validation/ValidationTypes.ts, src/validation/Validator.ts, test/functional/validation-functions-and-decorators.spec.ts
Adding enum validation decorator.
Currently there was no way of validating if a value was a valid enum and I noticed developers resorting to _hacky_ solutions like using `@Min` and `@Max` decorators to make sure value was inside the enum range. 
This PR solution aims to ease the validation of enums with number values.
Example usage
```
class MyClass {
@IsEnum(MyEnum)
someProperty: MyEnum;
}
```
=> Feature - Adding IsEnum validation rule

README.md, src/decorator/decorators.ts, test/functional/conditional-validation.spec.ts
This PR adds a new decorator `@IsOptional()` which checks if a value is is empty (=== '', === null) and if so, ignores all the validators on the property.
This decorator is equivalent to `@ValidateIf` with a condition checking for a missing value.  Example:
```
@ValidateIf((o)=> o.email !== "" && o.email !== null)
email: string;
```
This allows for a value to be completely optional for the purpose of validation, but if supplied, to be validated with existing validators.
=> Add IsOptional() decorator: if value missing, validators ignored

.editorconfig, src/validation/Validator.ts, test/functional/validation-functions-and-decorators.spec.ts
The `@IsEnum` validator does not support string enums yet.
Typescript 2.4+
```
enum MyEnum {
A = 'myString',
B = 'myOtherString'
}
```
Legacy
```
enum MyEnum {
A = <any>'myString',
B = <any>'myOtherString'
}
```
The issue with the current implementation is that we assume enum values are numbers:
```
/**
* Checks if a given value is an enum
*/
isEnum(value: any, entity: any): boolean {
const enumValues = Object.keys(entity)
.map(k => entity[k])
.filter(v => typeof v === "number") as number[];
return enumValues.indexOf(value) >= 0;
}
```
However, at runtime, the above enum examples produce:
```
{
'A': 'myString',
'B': 'myOtherString',
'myString': 'A',
'myOtherString': 'B'
}
```
thus making the following call
```
isEnum(MyEnum.A, MyEnum)
```
returns `false` instead of `true`.
Note: I ran …
=> Add string enum support for @IsEnum

README.md, src/decorator/decorators.ts
=> add support for undefined value in isOptional

README.md, src/decorator/decorators.ts, test/functional/conditional-validation.spec.ts
Allowing empty string in `@IsOptional ` opens a security hole in validation for datatypes other than string type. Additionally, it should behave similarly to "skipMissingProperties" which also skips validation only when the property is null or undefined
=> @IsOptional() and skipMissingProperties should have similar behaviour

README.md, src/validation/ValidationTypes.ts, test/functional/validation-functions-and-decorators.spec.ts
This is a Pull Request to address the issue identified in issue #57.
This Pull Request updates the default message for `@Length` as follows:
- `must be longer than` updated to `must be longer than or equal to`
- `must be shorter than` updated to `must be shorter than or equal to`
=> Fix for issue #57: @length(), default message wording

src/validation/Validator.ts
`value instanceof Date` is true for an invalid date. We should check if the date is valid.
=> fix(isDate): checking if the date is valid (issue #124)

CHANGELOG.md, src/validation/ValidationTypeOptions.ts
This updates the options that can be passed into `IsURL` to allow RegExp patterns to be supplied to whitelist and blacklist hosts. Currently only an array of strings are specified, but the underlying implementation checks RegExp as well: https://github.com/chriso/validator.js/blob/master/src/lib/isURL.js#L27
=> Update IsURLOptions to match underlying validator host list options

README.md
'each' is not supported for custom decorators. 
We do not check for each in metadata and do not handle it like here https://github.com/typestack/class-validator/blob/master/src/validation/ValidationExecutor.ts#L190
Take a look at https://github.com/typestack/class-validator/blob/master/src/validation/ValidationExecutor.ts#L213
=> Fix documentation on custom decorators

README.md
was removed previously from the readme but wasn't removed from the table of content
=> docs: remove installation sub sections from index

src/validation/ValidationTypes.ts
isPort which was used to check whether a given number was actaully a port was missing the default message thrown in case of falsy values.
=> fix: add default message for isPort validator

src/validation/ValidationExecutor.ts, src/validation/ValidatorOptions.ts, test/functional/validation-functions-and-decorators.spec.ts
PR for issue #308
previous dead pull request #353
=> feat: add `skipUndefinedProperties` and `skipNullProperties` options

src/decorator/decorators.ts, src/validation/Validator.ts, test/functional/validation-functions-and-decorators.spec.ts
This commit adds the feature to add locale to both isAlpha and isAlphanumeric with default as en-US
=> fix: add locale parameter for isAlpha and isAlphanumeric validators

src/validation/ValidationExecutor.ts, test/functional/validation-options.spec.ts
When `@Validate` + some custom constraint class is used with `{ each: true }`, then it is expected to be applied to each item of the target object field:
https://github.com/typestack/class-validator/issues/260
=> fix: apply custom constraint class validation to each item in the array

README.md, src/decorator/decorators.ts, src/validation/ValidationTypes.ts, src/validation/Validator.ts, test/functional/validation-functions-and-decorators.spec.ts
added isLatLong() which is used to check whether a given set of points is latitude and longitude or not. The validation is taken from validator.js
=> feat: add isLatLong, isLatitude, isLongtitude validators

src/validation/Validator.ts
I have refactored all `value` parameters correctly to `unknown` type. In short `unknown` type is like `any` but more strict because it forces you to make validation to it.
Before this PR lot of `value` looked like they have unneeded validation. For example:
```ts
isAscii(value: string): boolean {
return typeof value === "string" && this.validatorJs.isAscii(value);
}
```
In this case it looks odd that why we have to validate that `value` is a string since we are telling TS that it is already a string. Correct way of doing this is like here: 
```ts
isAscii(value: unknown): boolean {
return typeof value === "string" && this.validatorJs.isAscii(value);
}
```
This is correct since we cannot pass `value` to `this.validatorJs.isAscii` before we validate that the `value` is string 👍 
The side …
=> refactor: use unknown type for validation functions inputs

src/utils.ts, src/validation/ValidationExecutor.ts, test/functional/validation-options.spec.ts, test/utils.spec.ts
Looks like we do not support `each` option for Map and Set (https://github.com/typestack/class-validator/issues/428)
This PR add support Map/Set for regular validators and custom validators `@Validate`.
Also small unit tests added.
Close https://github.com/typestack/class-validator/issues/428
=> feat: support ES6 Map and Set for regular validators with each option

README.md, src/decorator/decorators.ts, src/validation/ValidationTypes.ts, src/validation/Validator.ts, test/functional/validation-functions-and-decorators.spec.ts
Hello, this PR should add the isHash validator using ValidatorJs
I've updated the doc
I've added tests but could you check if the tests need changes please ?
note: it doesn't support hash with uppercase letters yet, this was added to validatorjs (validatorjs/validator.js#1062) but is not released yet
=> feat: add isHash validator

README.md, src/decorator/decorators.ts, src/validation/Validator.ts
As validatorjs supports all option as well which was missing in class-validator. So adding this
=> feat: add all option in isuuid validator

README.md, src/decorator/decorators.ts, src/validation/Validator.ts
This PR is a reference to #412 . Now we can use the option strict = true for additional checks for a valid date, e.g. invalidates dates like 2019-02-29.
=> feat: add options for isISO8601 validator

README.md
=> docs: remove extra "/" in README

src/decorator/decorators.ts, src/index.ts, src/register-decorator.ts, src/validation/ValidationExecutor.ts
We can’t use `MetadataStorage` with DI because decorators are parsed before the very first call of `useContainer`, and therefore after the very fist call of `useContainer` the current `MetadataStorage` in the default container has been replaced with a brand new one without any metadata inside.
Possible runtime fix is to disable `MetadataStorage` in the `typedi` container:
```typescript
import {MetadataStorage, useContainer} from 'class-validator';
import {Container} from 'typedi';
useContainer(Container, {
fallback: true,
});
Container.set(MetadataStorage, null);
```
Closes #328.
Closes #261.
Closes #132.
=> fix: avoiding metadataStorage from DI

src/validation/Validator.ts
Validatorjs check if the string is a valid latitude-longitude coordinate in the format lat,long or lat, long.
Ref: https://github.com/validatorjs/validator.js
=> fix: switch isLatitude & isLongitude validators

src/validation/ValidationError.ts
I had this log method when an error was appearing : 
```ts
function logErrors(fieldErrors: { requestField: string; error: ValidationError }[]): void {
console.log(fieldErrors);
const errorMessages = fieldErrors
.map(({ requestField, error }) => `- ${requestField}: ${Object.values(error.constraints)}`)
.join('\n\t');
logger.error(new Error(`Bad request.\n\t${errorMessages}`));
}
``` 
This triggered a runtime error when error.constraints was undefined. This is the kind of error that could be avoided by Typescript check if the field was optional in ts declaration
ValidationError.constraint can be undefined if there is only a nested validation error
Maybe instead of changing the declaration, it's better to make sure the field is never undefined. We can discuss about this and I will modify the …
=> fix: optional `constraints` property in ValidationError

CHANGELOG.md, src/metadata/MetadataStorage.ts
Files that have typos:
```
src/metadata/MetadataStorage.ts:80:60: corrected "agains" to "against"
CHANGELOG.md:181:105: corrected "libary" to "library"
```
**PS:** I use [**client9/misspell**](https://github.com/client9/misspell) to scan typos
=> docs: fix typos across repo

README.md, src/decorator/string/IsDateString.ts, test/functional/validation-functions-and-decorators.spec.ts
`IsDateString()` decorator now aliased to `IsISO8601()` meaning both decorators have the same functionality.
Also added extra tests to make sure IsDateString is parsing ISO8601 dates correctly.
Also added documentation in `README.md` to make clear that the two decorators have same functionality.
- `npm run lint:check` passes
fixes #412
=> fix: alias IsDateString() decorator to IsISO8601()

src/decorator/string/IsPostalCode.ts
PostalCodeLocale in @types/validator.js does not include 'any' but isPostalCode should be able to receive it as a locale
[PostalCodeLocale in @types/validator.js ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/80922190a8125f052351520d07cb5166fc9b917b/types/validator/index.d.ts#L957)
=> fix: allow "any" as locale in isPostalCode decorator

README.md, src/validation/ValidationExecutor.ts, src/validation/ValidatorOptions.ts, test/functional/validation-options.spec.ts
Added an option to not detect more than one Error for each item.
- `npm run lint:check` passes (An error occurs outside of this PR.)
references #148, references #399, references #188
=> feat: add option to stop validation at first error

src/decorator/string/IsUUID.ts, test/functional/validation-functions-and-decorators.spec.ts
Fix typo in IsUUID.js error message, it should be `a UUID` instead of `an UUID`, since UUID is pronounced with a hard Y. Just like UFO.
=> fix: correct typo in IsUUID decorator

src/validation/ValidationError.ts, test/functional/whitelist-validation.spec.ts
When validation is performed with the `forbidNonWhitelisted` option, for any non-whitelisted properties, a `ValidationError` is created with the `children` property `undefined`. This breaks the current implementation of `ValidationError.toString()` which will try to map the `children` property, causing an error to be thrown. See #604.
This PR resolves the issue by testing `children` before mapping. Keeping the property optional feels semantically preferable to an empty list. The whitelist validation test is updated to cover this scenario.
- `npm run lint:check` passes
- [N/A] documentation added or updated
fixes #604
=> fix: do not throw in ValidationError.toString() error when using forbidNonWhitelisted option

src/validation/ValidationUtils.ts, test/functional/validation-functions-and-decorators.spec.ts
Format the `IsIn` validators error message constraints to be separated by "\<comma\>\<space\>", instead of "\<comma\>".
For example:
`"userType must be one of the following values: admin,user"`
becomes
`"userType must be one of the following values: admin, user"`
- `npm run lint:check` passes
fixes #625
=> fix: return errors separated <comma><space> instead of <comma> in IsIn decorator

package-lock.json, package.json, src/validation/ValidationUtils.ts
In 749fb26281a73ef43ce7e297f8b92be8a419c8cb, `@types/validator` was moved from `dependencies` to `devDependencies`. 
This causes those without `skipLibCheck` to set to `true` to get build errors, as `validator` is used in many of the generated type definitions.
This PR moves `@types/validator` back into `dependencies`.
- `npm run lint:check` passes
fixes #869
=> fix: Incorrect @types/validator dependency in latest version (0.13.0)
