.gitignore
.travis.yml
README.md
doc/release-notes.md
gulpfile.ts
package.json
src/decorator/decorators.ts
src/index.ts
src/register-decorator.ts
src/validation/ValidationExecutor.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/nested-validation.spec.ts
test/functional/reject-validation.spec.ts
test/functional/validation-functions-and-decorators.spec.ts
test/functional/validator-options.spec.ts
tsconfig.json

Make "options" optional in ValidationDecoratorOptions interface 

---

README.md

IsLongerThan example is not working. I think that "constraints" should be added.

Added missing constraints to IsLongerThan example

---

README.md
src/decorator/decorators.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/validation-functions-and-decorators.spec.ts

Creating validation for ISOString date

validate date iso string

---

src/validation/ValidationTypes.ts
test/functional/inherited-validation.spec.ts
test/functional/nested-validation.spec.ts
test/functional/validation-functions-and-decorators.spec.ts

I actually fixed this in my local copy at one time, then updated the package and lost it. Then someone opened a jira ticket complaining to me about the same issue I complained about (this pr issue)... so I finally decided to fix it.

minLength and maxLength inclusive error messages

---

gulpfile.ts
src/decorator/decorators.ts
src/index.ts
src/metadata/ConstraintMetadata.ts
src/validation/ValidationExecutor.ts
test/functional/validation-functions-and-decorators.spec.ts

Hi @pleerock ,
this pull request exposes the metadata storage service.
it fixes : 
- no tests was executed
- isEnum tests were not passing
- some typescript compilation error for isAlpha decorator and Validation Decorator [here](https://github.com/MagnusCloudCorp/class-validator/commit/a521a317e1f3c8faba28f2d1b9c86793d24649b3#diff-288d846ec06621fddacbd61e08486017R45)

Expose storage

---

README.md

The validation group example in the readme, does not produce the same results as described.
I assume the comment is wrong and not the implementation.

Fixed error in validation example

---

src/validation/ValidationExecutor.ts
src/validation/ValidationTypes.ts
test/functional/nested-validation.spec.ts

fix invalid nested

---

README.md
src/decorator/decorators.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/validation-functions-and-decorators.spec.ts

Similar to #96, but for numeric validation.

min and max inclusive error messages

---

package-lock.json
src/validation/Validator.ts
test/functional/validation-functions-and-decorators.spec.ts

Regex checked only if ISO date was present in the string, it should check if the entire string is ISO Date

Update IsDateString to match only entire ISO Date

---

src/decorator/ValidationOptions.ts

Fix custom message function signature typings

---

README.md
docs/basics/validating-objects.md

Added examples to readme and the docs

docs: add validateOrReject examples

---

test/functional/validation-functions-and-decorators.spec.ts

test: update tests to pass after validator.js update

---

src/validation/ValidationTypes.ts

Hello, this should fix issue #287 
It add a default message for the isMilitaryTime validator

fix: add default message for isMilitaryTime validator

---

src/validation/ValidationExecutor.ts

fix: create instance of ValidationError for whitelist errors

---

README.md
src/decorator/decorators.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/validation-functions-and-decorators.spec.ts

Hello, this PR should add the isJWT validator using ValidatorJs
I've updated the doc and added some test tell me if I missed something

feat: add isJWT validator

---

src/validation/ValidationExecutor.ts
test/functional/custom-decorators.spec.ts
test/functional/validation-options.spec.ts

Context wasn't being passed in for isDefined and custom validators.
https://github.com/typestack/class-validator/issues/292

fix: pass context for isDefined and custom validators

---

README.md
src/decorator/decorators.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/validation-functions-and-decorators.spec.ts

Hello, this should add the isISSN validator

feat: add isISSN validator

---

README.md
src/decorator/decorators.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/validation-functions-and-decorators.spec.ts

Hello, this should add the isMACAddress validator

feat: add isMACAddress validator

---

README.md

docs: various grammatical fixes in README

---

src/decorator/ValidationOptions.ts

chore: fix typos in comments of ValidationOptions interface

---

README.md
package-lock.json
src/decorator/decorators.ts
src/validation/ValidationTypes.ts
src/validation/Validator.ts
test/functional/reject-validation.spec.ts
test/functional/validation-functions-and-decorators.spec.ts

This PR adds support for Firebase-style PushIds, you can see more about the science and inner-workings here: https://firebase.googleblog.com/2015/02/the-2120-ways-to-ensure-unique_68.html
**Overview**
Simply, we're checking:
- The input must be a string
- The string must be 20 characters in length
- The string must only contain web-safe characters
I've checked the backlog and PRs for duplicates and found nothing.

feat: add IsFirebasePushId validator

---

README.md

Change `minDate` to `maxDate` on `validator.maxDate`

docs: fix typo on README

---

src/decorator/decorators.ts

What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```
Issue Number: #555 
Apply all decorators with return type `PropertyDecorator` from typescript
```
[ ] Yes
[x] No
```

fix: apply all decorators type PropertyDecorator

---

src/validation/ValidationExecutor.ts
test/functional/custom-decorators.spec.ts

Closes issue https://github.com/typestack/class-validator/issues/480

fix: pass context to ValidationError for async validations

---

README.md
src/validation/ValidationExecutor.ts
test/functional/nested-validation.spec.ts

@NoNameProvided This PR aims to fix https://github.com/typestack/class-validator/issues/538

fix: ValidateNested support multi-dimensional arrays

---

README.md

I think it would be handy to have the limitation described in this PR. Took me almost an hour to find closed issue #281.

docs: added note about nested validation and object creation

---

src/decorator/string/MaxLength.ts

Simple change, but this threw me off for a second.

chore: correct name in MaxLength validation decorator

---

src/decorator/common/IsIn.ts
src/decorator/common/IsNotIn.ts
test/functional/validation-functions-and-decorators.spec.ts

feat: allow readonly array argument for IsIn IsNotIn validators

---

src/decorator/common/ValidateIf.ts
src/decorator/typechecker/IsBoolean.ts
src/decorator/typechecker/IsDate.ts

Fixes documentation for decorators:
- `ValidateIf`
- `IsBoolean`
- `IsDate`

Fixes incorrect decorator documentation

---

src/decorator/string/Matches.ts
test/functional/validation-functions-and-decorators.spec.ts

fix: matches decorator with modifier as string

---

src/decorator/object/IsNotEmptyObject.ts
test/functional/validation-functions-and-decorators.spec.ts

_Note: PR description was moved to issue for easier discoverability by @NoNameProvided ._
references #678.

feat: add nullable option for IsNotEmptyObject rule.
